### ISSUE TITLE
Upgrade xmldom to resolve critical vulnerability

### ISSUE THREAD

**Issue by kyoshino** [maptiler/maptiler-sdk-js#103]
Running [`pnpm audit`](https://pnpm.io/cli/audit) in my project finds two vulnerabilities in `xmldom` used in the SDK JS:

- **Critical**: https://github.com/advisories/GHSA-crh6-fp67-6883
- Moderate: https://github.com/advisories/GHSA-5fg8-2547-mr8q

[`xmldom`](https://www.npmjs.com/package/xmldom) is now published as [`@xmldom/xmldom`](https://www.npmjs.com/package/@xmldom/xmldom). Please replace the package name and update to the latest version.

https://github.com/maptiler/maptiler-sdk-js/blob/82d6e686c642e091bb533e7b8fba52ceceb2cd58/package.json#L66

In the meantime, I have an [override](https://pnpm.io/package_json#pnpmoverrides) in `package.json` to work around the issue:

```json
  "pnpm": {
    "overrides": {
      "xmldom": "npm:@xmldom/xmldom"
    }
  }
```

**Comment by jonathanlurie** [comment]
Hello @kyoshino , thanks for the feedback. We just included this as part of our next release. I'll let you know when it's out.

**Comment by sp7923** [comment]
Hello , can you pls suggest any present solution for the problem until the latest version is released as by using the above override my maptiler is working but when I try installing other packages like express-mongo-sanitize and sanitize-html npm error is encountered. 
verbose stack TypeError: Invalid Version: npm:@xmldom/xmldom

**Comment by kyoshino** [comment]
I don’t see any error when running `pnpm add express-mongo-sanitize` or `pnpm add sanitize-html`, but the issue could perhaps be solved by just adding a version:

```json
  "pnpm": {
    "overrides": {
      "xmldom": "npm:@xmldom/xmldom@^0.8.0"
    }
  }
```

**Comment by jonathanlurie** [comment]
Hello, apologies for the very late feedback. The xmldom package was replaced by the more recent and maintained @xmldom/xmldom so the issue should no longer show up
