### ISSUE TITLE
setData does not exists on type Source

### ISSUE THREAD

**Issue by AdamZajler** [maptiler/maptiler-sdk-js#108]
I'm following the tutorial https://docs.maptiler.com/sdk-js/examples/live-update-feature/. 
![image](https://github.com/user-attachments/assets/e1a5676b-d583-42a4-b91e-11abc67d1869)

But my IDE is yelling that `setData` method does not exist on type Source :open_mouth: 

![image](https://github.com/user-attachments/assets/955887ce-d2d2-4f65-8efe-7c7c3f582dbf)

I have checked it on my co-worker IDE (VS code vs WebStorm); but he have the same issue. 

Am I doing smth wrong? 

I'm using React 18.2 + maptiler/sdk 2.2.2

**Comment by jonathanlurie** [comment]
Hello @AdamZajler , apologies for the late reply. The `Map` method `.getSource()` returns a `Source`, but `Source`  is only an interface in TS, not a class, and it does not contain the method `.setData()`. This interface is being implemented by a few classes, but only `GeoJSONSource` adds the method `.setData()`.

As a result, VSCode intelliSense cannot be sure that `map.getSource("...")` will return a `GeoJSONSource`, it only knows for sure that it returns a `Soucre`, and this is why `.setData()` is not part of the list.

If you want to check programmatically that your source is specifically a `GeoJSONSource`, you will have to check that the `.type` attribute of your source is equal to `"geojson"` and then you will have to *cast* it to a `GeoJSONSource`:

<img width="1072" alt="Screenshot 2024-09-06 at 09 57 27" src="https://github.com/user-attachments/assets/852dbb63-7c9f-43ef-af21-217887f5c685">
