### ISSUE TITLE
Bunch of undocumented (typescript) functions

### ISSUE THREAD

**Issue by Matsuuu** [maptiler/maptiler-sdk-js#117]
Heya,

Just started using MapTiler and have gone through a bunch of yall's examples. 

The current version (2.3.0) has a lot of missing typescript type definitions, causing a lot of editor level errors and development-time headache.

e.g. https://docs.maptiler.com/sdk-js/examples/default-marker/

```javascript
const marker = new maptilersdk.Marker({ element: MyElem }).setLngLat(location).addTo(map);
```

This code will complaing about 2 things:

- "Expected 0 arguments, but got 1. "
- "Property 'setLngLat' does not exist on type 'Marker'."

Is this just an error in the buildprocess, a downside of extending the `maplibre-gl`  or something in between?

---

Edit: 

I noticed that I was able to get somewhat coherent typings by including the MapLibre type definition in the type casting. This of course isn't the optimal experience but a workaround. 

I'll be glad to hear back from yall and hear what you think we should do with this.

```javascript
import * as maptilerSdk from "@maptiler/sdk";
import { Map as LibreMap } from "maplibre-gl";

export async function createMap(target, location) {

    const map = new maptilerSdk.Map({
        container: target,
        style: MAP_STYLE,
        center: location,
        zoom: 15,
        navigationControl: false,
        apiKey: MAPS_API_KEY,
    });

    return /** @type { maptilerSdk.Map & LibreMap } */ (map);
}
```

**Comment by jonathanlurie** [comment]
Hello again, can you try the same but with the property `moduleResolution` set to `Bundler` in your tsconfig ? I believe that should solve the issue.

**Comment by Matsuuu** [comment]
Heya,

I was going to create a reproduction of this issue but ended up having a bit of a struggle to reproduce this.

Some of my findings and how I ended up fixing it: 

---

**If a project is using a `jsconfig.json`**

If a project is using a minimal jsconfig.json, this library works pretty much out of the box without issues

**If a project is using `tsconfig.json`**

If the project uses a tsconfig.json (wether it's for ts or js files), you needed to enable the `esModuleInterop` flag to make the typescript language server to scan through maplibre dependencies for the "deeper" types.

I think this might be worth popping into some of the docs pages

**Comment by jonathanlurie** [comment]
Thanks for the `esModuleInterop` tip! As it's not always possible to have `moduleResolution` set to `bundler`, that's probably a fit for more projects,

**Comment by Matsuuu** [comment]
Yeah. Glad to get this resolved. Agree that moduleResolution: bundler isn't really a silver bullet especially in a world where many people work without bundlers.

I'm closing this now as it's resolved. Thanks for swift feedback!

**Comment by jonathanlurie** [comment]
Thanks! I will make sure we add a line about this in our documentation!
