### ISSUE TITLE
Typing issue with WindLayer

### ISSUE THREAD

**Issue by eugbyte** [maptiler/maptiler-sdk-js#128]
For the following code
```
import { WindLayer } from "@maptiler/weather";

const weatherLayer = new WindLayer();
weatherLayer.on("tick", () => console.log("animating"));
```

Typescript compiler complains that: `Property 'on' does not exist on type 'WindLayer'.` , but it works on run time.

I know that WindLayer is from the `@maptiler/weather` repository, but since that repository is likely private, I am posting here.

**Comment by jonathanlurie** [comment]
Hello @eugbyte ,
in some cases, this happens due to Maplibre being a commonJS bundle. Can you try one of the two approach listed here https://github.com/maptiler/maptiler-sdk-js?tab=readme-ov-file#typescript ?
