### ISSUE TITLE
MaptilerNavigationControl not available in the maptiler-sdk.d.ts

### ISSUE THREAD

**Issue by StazriN** [maptiler/maptiler-sdk-js#34]
`MaptilerNavigationControl` is not defined in the `maptiler-sdk.d.ts` so it can't be used in the TypeScript file like is shown in the example: https://docs.maptiler.com/sdk-js/api/controls/#navigationcontrol

My code:
```js
import * as MapTilerSDK from '@maptiler/sdk';

const map = new MapTilerSDK.Map({
    container: element,
    center: new MapTilerSDK.LngLat(this.center.longitude, this.center.latitude),
    zoom: this.zoomLevel,
    style: MapTilerSDK.MapStyle.STREETS,
    navigationControl: false,
});

const nav = new MapTilerSDK.MaptilerNavigationControl(); // TS2551: Property 'MaptilerNavigationControl' does not exist on type 'typeof import(".../node_modules/@maptiler/sdk/dist/maptiler-sdk")'. Did you mean 'NavigationControl'?
map.addControl(nav, 'top-left');
```

Can you please add `MaptilerNavigationControl` to the `maptiler-sdk.d.ts`?

**Comment by jonathanlurie** [comment]
Hello @StazriN , 
thanks for reporting that! You're right, it's not there! I will add that asap and let you know.

**Comment by jonathanlurie** [comment]
Hey @StazriN ,
this is now fixed as part of [this commit](https://github.com/maptiler/maptiler-sdk-js/commit/2a645a72deb0cc2243480e04d780b9d221dd001a). Version [v1.0.11](https://github.com/maptiler/maptiler-sdk-js/releases/tag/v1.0.11) pushed on [NPM](https://www.npmjs.com/package/@maptiler/sdk).

**Comment by StazriN** [comment]
Hi @jonathanlurie,
Thank you so much for the fast fix! You're awesome!
