### ISSUE TITLE
Compact attribution control not working

### ISSUE THREAD

**Issue by tomislav** [maptiler/maptiler-sdk-js#37]
I'm trying to get the compact attribution control, but it always shows up expanded.

```
    map = new maptilersdk.Map({
      container: 'map-canvas',
      style: default_style,
      zoom: 16,
      center: center_coord,
      maptilerLogo: false,
      attributionControl: false
    });

    map.addControl(new maptilersdk.AttributionControl({
      compact: true
    }));
```

<img width="477" alt="Screenshot 2023-06-19 at 13 21 53" src="https://github.com/maptiler/maptiler-sdk-js/assets/656/98645f6d-14d9-476f-9134-42c50dc3ede9">

**Comment by jonathanlurie** [comment]
Hello @tomislav , I will look into this!

**Comment by jonathanlurie** [comment]
Hello again,
the compact attribution is always expanded at first and then would take its compact form only after the map is being panned by the user, to ensure the end user had a chance to be informed. Note that this is already the behavior [implemented by Maplibre](https://maplibre.org/maplibre-gl-js-docs/api/markers/#attributioncontrol) and we felt was appropriate to keep in the SDK.
Best.

**Comment by tomislav** [comment]
Hmmm... by reading the [docs](https://docs.maptiler.com/sdk-js/api/controls/#attributioncontrol), I was expecting it to be collapsed if the map is less than 640px wide. It just takes a lot of space on mobile. We're looking to replicate the Apple Maps look that only shows an apple.

`If true , force a compact attribution that shows the full attribution on mouse hover. If false , force the full attribution control. The default is a responsive attribution that collapses when the map is less than 640 pixels wide. Attribution should not be collapsed if it can comfortably fit on the map. compact should only be used to modify default attribution when map size makes it impossible to fit default attribution and when the automatic compact resizing for default settings are not sufficient.
`

**Comment by tomislav** [comment]
[Maplibre's docs](https://maplibre.org/maplibre-gl-js-docs/api/markers/) are a little different than [yours](https://docs.maptiler.com/sdk-js/api/controls/#attributioncontrol) :)

`If true , the attribution control will always collapse when moving the map. If false , force the expanded attribution control. The default is a responsive attribution that collapses when the user moves the map on maps less than 640 pixels wide. Attribution should not be collapsed if it can comfortably fit on the map. compact should only be used to modify default attribution when map size makes it impossible to fit default attribution and when the automatic compact resizing for default settings are not sufficient.`

**Comment by jonathanlurie** [comment]
From what I understand, you would like the attribution to be collapsed even before the first interaction, right?

**Comment by tomislav** [comment]
Yes, if the screen width is less than 640 pixels (mobile).

**Comment by jonathanlurie** [comment]
Sorry for the late reply @tomislav . At the moment it's not possible but we'll discuss internally about this topic!
