### ISSUE TITLE
An error occurred while adding the weather layer

### ISSUE THREAD

**Issue by tangzijun** [maptiler/maptiler-sdk-js#43]
I get an error when I add the weather layer, how can I fix it

![image](https://github.com/maptiler/maptiler-sdk-js/assets/11813048/816ef372-297e-4e32-a4b6-cea8a90a31ff)

![image](https://github.com/maptiler/maptiler-sdk-js/assets/11813048/0aa3d7ad-c215-4ac8-9d44-44a8b0343ac5)

**Comment by jonathanlurie** [comment]
Hello @tangzijun , the water layer is spelled with a capital "W", so you should have something like this:

```ts
map.setPaintProperty("Water", "fill-color", "rgba(0, 0, 0, 0.5)");
map.addLayer(layer, "Water");
```

Best.
