### ISSUE TITLE
toBounds is not a function

### ISSUE THREAD

**Issue by gwonen** [maptiler/maptiler-sdk-js#57]
Am I going crazy or is https://docs.maptiler.com/sdk-js/api/geography/#lnglat#tobounds not currently implemented? I can't find any reference to it in the code.

**Comment by CraigglesO** [comment]
👋 Hey @gwonen , you are correct it no longer exists.
The current SDK is a wrapper around maplibre-gl-js 3.1.0 and the version 3 change was to [migrate away from toBounds](https://github.com/maplibre/maplibre-gl-js/pull/2188)
You actually want to use [LngLatBounds](https://github.com/maplibre/maplibre-gl-js/blob/v3.1.0/src/geo/lng_lat_bounds.ts) now instead. Hopefully soon the docs will reflect this change as well. Apologies for the confunsion.

**Comment by bolollo** [comment]
Fixed now in https://docs.maptiler.com/sdk-js/api/geography/#lnglatbounds.fromLngLat
