### ISSUE TITLE
Update @maptiler/weather

### ISSUE THREAD

**Issue by sommmen** [maptiler/maptiler-sdk-js#81]
Hiya, seems the weather module needs to be updated to be compatible with the latest maptiler sdk?

https://www.npmjs.com/package/@maptiler/weather

**Comment by jonathanlurie** [comment]
Hello @sommmen , thanks for reporting the issue. You're right, I will try to address that today, sorry for the inconvenience.

**Comment by jonathanlurie** [comment]
BTW @sommmen do you mind describing the issue you are having with the Weather Library + SDK? If it's for instance
- NPM yelling for version conflicts
- TypeScript yelling for type incompatibility
- a runtime error
- other?

**Comment by sommmen** [comment]
> BTW @sommmen do you mind describing the issue you are having with the Weather Library + SDK? If it's for instance
> 
>     * NPM yelling for version conflicts
> 
>     * TypeScript yelling for type incompatibility
> 
>     * a runtime error
> 
>     * other?

![giphy 1](https://github.com/maptiler/maptiler-sdk-js/assets/8641495/45285450-0be9-4559-a6ca-46e3d4aa9491)

(the npm yelling one).

**Comment by jonathanlurie** [comment]
I see, thanks!
