### ISSUE TITLE
Make maker PopUp clickable

### ISSUE THREAD

**Issue by frederikheld** [maptiler/maptiler-sdk-js#88]
Is there any way to make a Marker `Popup` clickable? I could not find any information on that in the docs nor in the examples.

The only hack I found was wrapping the whole Popup content into an `a` tag.

```
    const location = ...
    const lngLat = ...

    const content =
      '<a href="/locations/' +
      location.id +
      '"><p><b>' +
      location.name +
      '</b><p><p>' +
      location.abstract +
      '</p></a>'

    const popup: Popup = new Popup({
      closeOnClick: true,
      subpixelPositioning: true,
      closeButton: false
    })
      .setLngLat(lngLat)
      .setHTML(content)
```
Unfortunately this is not a feasible solution as I'm using Maptiler in an SPA app and I need it to call a SPA route, not do a full page reload.

So I'm looking for a way to hook into the `onClick` event of the popup.

Is this possible?

**Comment by frederikheld** [comment]
I found the `setDOMContent()` function and came up with this:

```js
    const location = ...
    const lngLat = ...

    const content = document.createElement('div')
    content.addEventListener('click', () => selectLocation(location))
    content.innerHTML =
      '<div><p><b>' +
      location.name +
      '</b></p><p>' +
      location.abstract +
      '</p></div>'

    const popup: Popup = new Popup({
      closeOnClick: true,
      subpixelPositioning: true,
      closeButton: false
    })
      .setLngLat(lngLat)
      .setDOMContent(content)

    const marker: Marker = new Marker({ color: '#FF0000' })
      .setLngLat(lngLat)
      .setPopup(popup)
      .addTo(mapInstance)
```

It works well, but is this the canonical way to do this?

And how would I make the marker not only show the popup but also center on the map when it is tapped? Again I found no way to hook into the respective event.

**Comment by jonathanlurie** [comment]
Hello @frederikheld , apologies for the late answer.

I must admit that there is room for improvement on binding event to popups! I found a custom solution that could be something we add to the SDK in the future.

The solution consists in binding an event to the DOM element that is contained in the popup, but a new DOM element is being created eveytime the popup pops! So we cannot just keep a reference to it, we have to, itself, bind it to the "open" event of the popup. Here is a sample with two popups and their markers:

```js
// This function binds the html element inside a popup
// to a given event (cb).
// The call to addEventListener is made everytime the popup
// is open because MapLibre/MapTiler SDK create a new DOM element
// every time the popup is being opened
function bindEvent(popup, eventName, cb) {
  popup.on("open", () => {
    popup.getElement().addEventListener(eventName, () => {
      cb.call(null, popup);
    })
  })
}

// Animate the map to center it on the popup coords
function centerMapOnPopup(popup, map) {
  map.easeTo({
    center: popup.getLngLat()
  })
}

const map = new maptilersdk.Map({
  container: document.getElementById("map-container"),
  center: [-96, 37.8],
  zoom: 3
})

// Create a first popup
const lngLat1 = [-110, 37.8];
const popup1 = new maptilersdk.Popup({
  closeOnClick: false,
  subpixelPositioning: true,
  closeButton: false
})
  .setLngLat(lngLat1)
  .setHTML("<h1>I'm Popup 1</h1>")
  .addTo(map);

// Create the marker that is paired with the first popup
const marker1 = new maptilersdk.Marker({ color: '#FF0000' })
  .setLngLat(lngLat1)
  .setPopup(popup1)
  .addTo(map)

// Add a custom "click" event to the popup
bindEvent(popup1, "click", (p) => {
  centerMapOnPopup(p, map)
})

// Do the same with a second popup
const lngLat2 = [-92, 37.8];
const popup2 = new maptilersdk.Popup({
  closeOnClick: false,
  subpixelPositioning: true,
  closeButton: false
})
  .setLngLat(lngLat2)
  .setHTML("<h1>I'm Popup 2</h1>")
  .addTo(map);

const marker2 = new maptilersdk.Marker({ color: '#00FF00' })
  .setLngLat(lngLat2)
  .setPopup(popup2)
  .addTo(map)

bindEvent(popup2, "click", (p) => {
  centerMapOnPopup(p, map)
})
```

Notice how with this `cb.call(null, popup);` we are exposing the `popup` instance as an argument of the callback. I find it convenient to scope what you want to do with this popup but of course feel free to adapt this to your preference.

Let me know if that helps!

**Comment by frederikheld** [comment]
Thank your for your response. Especially useful is the information that the event listener will created every time the popup pops.
If I understand my approach correctly, I will have a separate popup for each marker. IDK if this is a good thing performance wise, but it helps with positioning as opposed to have one popup for all markers that needs to be moved into the correct place. My first approach used one popup for all and it wasn't placed correctly using the `setLngLat()` function.

If the listener is created every time the popup pops, it should be possible to automatically destroy the listener by using the [`once`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#once) option. I just have to make sure that the popup closes when clicked, otherwise it can't be clicked again.

 I'll look into it.
